Fix copying multiple env files
Previously the env file copying worked properly only when there was one
env file and it was called ".env".

*   If there were multiple env files, including .env, dkp copied the
    content of .env into all of them (because "info.env_file" always
    pointed to ".env").

*   If there were multiple env files, but no ".env", dkp crashed:

    FileNotFoundError: [Errno 2] No such file or directory:
    '.../test-data/.env'

Now dkp copies every .env and *.env file with its own content.